Chore/ci (#2)
* Add ci config

* Fix ruby-version

ci failed because of ruby version

```terminal
Using Docker executor with image ruby:2.5 ...
$ RAILS_ENV=test bundle install --jobs $(nproc) "${FLAGS[@]}"
Your Ruby version is 2.5.1, but your Gemfile specified 2.5.0
ERROR: Job failed: exit code 1
```

* Add test database config for gitlab ci

https://medium.com/@steven.jackson/configuring-a-gitlab-ci-pipeline-for-rails-postgresql-and-rspec-57c411400172

* Fix filename

```
renamed:    config/database.html.gitlab -> config/database.yml.gitlab
```

* Fix ci config

Add redis/nodejs/yarn

```
$ RAILS_ENV=test bundle exec rake db:create db:schema:load
rake aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'uglifier'.
Gem Load Error is: Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.
```

* Fix ci config:remove sudo

* Add presto gem

* Modify rubocop rule

* Fix rubocop rule

* Add  # frozen_string_literal: true

* Change pronto to rubocop on ci

* Add code quality on ci

* Modify code quality

* Modify codequality

* Fix on ci

* Fix ci

* Add circleci

* Chore for CI

* Fix database setting for circleci

* Fix database name of parameter

* Change circleci

* Fix db setting

* Fix ci

* Fix ruby version on ci

* Fix remove yarn on ci

* Fix change image on ci

* Add npm package(test)

* Add hashid gem

for updating Gemfile/Gemfile.lock

* Add rspec junit gem

* Add fail test

* Fix fail test

* Fix rspec on ci

* Fix to pass sample spec

* Remove test spec

* Add rubocop on circleci