Fix ruby-version
ci failed because of ruby version

```terminal
Using Docker executor with image ruby:2.5 ...
$ RAILS_ENV=test bundle install --jobs $(nproc) "${FLAGS[@]}"
Your Ruby version is 2.5.1, but your Gemfile specified 2.5.0
ERROR: Job failed: exit code 1
```